on: 
 push:
  branches:
    - "feature/TP-*/*"
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: echo "hola job"


